const COMMENTS_DATABASE = {
    savage: {
        extreme: [
            "has more red flags than a cricket stadium during India vs Pakistan match. Proceed with industrial-grade caution.",
            "is the human equivalent of a 404 error—personality not found, but plenty of demands.",
            "is basically a LinkedIn profile disguised as a human. Do you want a spouse or a senior dev?",
            "is keeping colonial beauty standards deeper than their own education. 👏",
            "has a biodata that reads like a ransom note. Give us the money (package) or the rishta dies.",
            "is living in a 1970s Bollywood movie while expecting 2025 salaries. The delusion is cinematic.",
            "is clearly looking for a servant with a degree, not a partner. Red flag doesn't even cover it.",
            "has an ego so large it needs its own pin code. Good luck fitting that into a 2BHK.",
            "is likely the reason why their relatives have started 'unfollowing' them on life.",
            "is a walking 'Terms and Conditions' page—nobody reads it, but everyone regrets agreeing.",
            "is effectively asking for a green card with a heartbeat. We respect the hustle, not the person.",
            "has expectations that higher than the Burj Khalifa but a personality flatter than a chapati.",
            "is proof that some people use biodatas as a creative writing exercise for fiction.",
            "is an 'onion' profile—the more you peel, the more you want to cry.",
            "is basically a 'Proceed at your own risk' sign in human form.",
            "is looking for a 10/10 partner while being a solid 2.2 on a good day. Statistics hate you.",
            "has a biodata that should be studied by NASA to understand black holes—where logic disappears.",
            "is the reason why 'No' was invented as a full sentence.",
            "is purely looking for an ATM that can cook. Or a cook that can be an ATM.",
            "is an absolute emotional skyscraper—mostly glass, very cold, and liable to break.",
            "expects the partner to be 'modern yet traditional', which means 'do everything I say while wearing a saree'.",
            "is as flexible as a brick. Good luck building a marriage on that foundation.",
            "has a personality that's still buffering... and the Wi-Fi just got cut.",
            "is a 'VIP'—Very Irritating Person. The rishta is the invitation to a lifetime of headache.",
            "is effectively a 'System Error'—please restart your life and try again.",
            "is looking for a soulmate but would settle for a high credit score and a fair complexion.",
            "is basically a WhatsApp forward—full of fake news and unwanted by most.",
            "is a 'masterpiece'—mostly because they belong in a museum of ancient mindsets.",
            "is the human embodiment of 'Reply All' when only one person needed to see it.",
            "is a walking disaster zone, and the insurance doesn't cover this marriage.",
            "wants a 'homely' partner, which is just code for 'someone my mom can bully'.",
            "is a 'Limited Edition'—limited brains, limited manners, unlimited demands.",
            "has a biodata that smells like old mothballs and unearned entitlement.",
            "is essentially a pop-up ad—annoying, persistent, and usually full of malware.",
            "is looking for a partner to 'complete' them, because half of them is already missing.",
            "is a 'Mystery'—mostly because we can't figure out why they're still single... Oh wait, we just did.",
            "is as warm as a freezer and twice as loud. The marriage will be a literal chill zone.",
            "is effectively a 'No Entry' sign for happiness.",
            "is looking for a 'settled' partner because they've never been settled a day in their life.",
            "is a 'Classic'—in the sense that they're totally outdated and hard to maintain.",
            "is basically a 'Loading...' screen that never finishes. Just move on.",
            "is a 'Flashback'—they keep bringing up things from 500 years ago as requirements.",
            "is purely atmospheric—all gas and no substance.",
            "is the final boss of matrimonial entitlement. Level 100 Boss.",
            "is a 'Draft'—not ready for public release, keep in the bin.",
            "is basically a 'Broken Link'—leads nowhere and wastes everyone's time.",
            "is a 'Notification'—distracting, usually unimportant, and better left ignored.",
            "is looking for a 'perfect' match because they're allergic to reality.",
            "is as sweet as a lemon and just as sour when things don't go their way.",
            "is a 'Legend'—only in their own mind.",
            "is effectively a 'Waitlist'—but nobody is actually waiting."
        ],
        moderate: [
            "is giving mixed signals like Mumbai traffic. Some hope exists, but pack patience and a lot of paracetamol.",
            "is a 'decent' catch, if your definition of decent includes 'mildly delusional'.",
            "is the human embodiment of 'wheatish'—diplomatic, confused, and trying to please everyone.",
            "has a personality that feels like it was copy-pasted from a 2010 Facebook status.",
            "is safe. Like choosing vanilla when there's 50 other flavors. Boring, but predictable.",
            "is basically a 'Maybe'. Not a 'Yes', not a 'No', just a long sigh.",
            "is the reason why 'arranged marriage' is often called a 'compromise'.",
            "is as interesting as a plain digestive biscuit. Healthy? Maybe. Exciting? Never.",
            "is a 'Budget' version of a dream partner. All the basics are there, but the features are missing.",
            "is effectively a 'Seen' message at 2 AM. You know they're there, but do you really care?",
            "is looking for a 'simple' life, which is code for 'I don't have any hobbies'.",
            "is as reliable as a 10-year-old car—it runs, but you're always waiting for the engine light.",
            "is the human equivalent of 'Standard Shipping'—it'll get there eventually, but don't expect much.",
            "is a 'Starter Pack' partner. Good for beginners, but you'll want to upgrade soon.",
            "is effectively a 'Placeholder' in the matrimonial market.",
            "is looking for 'mutual respect', which usually means 'don't talk back when I'm wrong'.",
            "is as deep as a puddle after a light drizzle. Refreshing at first, then just messy.",
            "is a 'Standard Operating Procedure'—follow the rules and nobody gets hurt.",
            "is basically a 'Background Character' in their own life story.",
            "is looking for a 'soulmate' but would settle for someone who tolerates their snoring.",
            "is as adventurous as ordering the same dish at the same restaurant for 20 years.",
            "is a 'Safe Bet'—you won't lose much, but you won't win the lottery either.",
            "is effectively a 'Draft Email'—they've said what's needed, but haven't hit 'send' on life.",
            "is looking for 'understanding', which means 'understand that I am always right'.",
            "is as stable as a table with one short leg. You can use it, but things might slide off.",
            "is a 'Classic Rock' fan who thinks music ended in 1985. The vibe is... vintage.",
            "is basically a 'To-Do List'—everything is planned, nothing is spontaneous.",
            "is looking for a 'well-settled' life, but they're still figuring out how to use a microwave.",
            "is as unique as a white t-shirt. Useful, everywhere, and easily replaceable.",
            "is effectively a 'Free Trial'—everything looks good for 30 days, then the real work starts.",
            "is looking for 'chemistry' but they failed it in high school. The irony.",
            "is as deep as a TikTok caption. Looks profound, but it's just a lyric.",
            "is a 'Middle Management' partner—handles things, but doesn't really the lead.",
            "is basically a 'Screen Saver'—looks okay while you're waiting for something else.",
            "is looking for 'balance', which means 'balance my life while I do whatever I want'.",
            "is as exciting as a spreadsheet. But hey, some people love Excel!",
            "is effectively a 'Status Update'—mostly for show, rarely for substance.",
            "is looking for 'honesty', which means 'tell me I'm beautiful every day'.",
            "is as predictable as a Star Plus serial. Drama at 8 PM, guaranteed.",
            "is a 'DIY' partner—lots of potential, but requires significant assembly.",
            "is basically a 'Template'—vague, generic, and fits everywhere but nowhere.",
            "is looking for 'space', which they already have plenty of in their head.",
            "is as deep as the 'shallow end' of the pool. Safe for children, boring for adults.",
            "is effectively a 'Bookmark'—holding the spot until something better comes along.",
            "is looking for 'growth', but they haven't changed their hairstyle since 11th grade.",
            "is as bright as a 20-watt bulb. Provides light, but you can't really see the future.",
            "is a 'Beta Version'—needs a few more updates before the full release.",
            "is basically a 'Ringtone'—you get used to it, but sometimes you just want it on silent.",
            "is looking for 'peace', but they're the one starting the wars.",
            "is as flexible as a frozen yoga mat. Good luck with the poses."
        ],
        chill: [
            "is surprisingly reasonable for arranged marriage. Either honest or forgot to lie. Either way, respect!",
            "is a rare breed—someone who doesn't think their salary is a substitute for a personality.",
            "is basically a hero for not using the word 'homely' more than three times.",
            "actually seems like a person you could have a conversation with. Suspicious.",
            "is the 'least likely to be featured on a reality show' candidate. A solid win.",
            "is a 'Breath of Fresh Air' in a market full of stale requirements.",
            "is effectively a 'Green Flag'—but we're still looking for the hidden fine print.",
            "is looking for a partner, not a project. We love the maturity!",
            "is as normal as a 'Correct' answer. It's almost boring how not-crazy they are.",
            "is basically a 'Golden Retriever'—happy to be here, easy to please, and generally liked.",
            "is the human equivalent of a 'Relaxed' fit—comfortable and doesn't try too hard.",
            "is looking for 'connection' and actually knows what that word means. 👏",
            "is as reliable as a 'Trusted' source. You can actually believe what they say.",
            "is effectively a 'Low Maintenance' partner. A dream for the lazy!",
            "is looking for 'shared values' and doesn't just mean 'bank balance similarities'.",
            "is as clear as 'HD'. No pixels, no mystery, just honesty.",
            "is basically a 'Premium' version of a human. High quality, low drama.",
            "is looking for 'fun' and doesn't think 'watching TV' is a personality trait.",
            "is as balanced as a 'Perfectly' tuned instrument. Ready for a duet!",
            "is effectively a 'First Class' catch. Enjoy the legroom!",
            "is looking for 'growth' and actually reads books that aren't for an exam.",
            "is as sweet as 'Homemade' mithai. No preservatives, just pure vibes.",
            "is basically a 'Soul'—not just a self-profile.",
            "is looking for 'adventure' and has actually left their city in the last year.",
            "is as solid as a 'Rock'. Reliable foundation for a life together.",
            "is effectively a 'Rare Find'—like a 2000 rupee note in an old jeans pocket.",
            "is looking for 'intellectual' connection and doesn't mean 'comparing marksheets'.",
            "is as bright as a 'Sunny' day. Hard to be in a bad mood around them.",
            "is basically a 'Natural'. No filters needed, the vibe is just right.",
            "is looking for 'support' and is actually willing to give some back.",
            "is as deep as 'The Ocean'. There's always more to discover.",
            "is effectively a 'Masterpiece'—and for once, it's not a self-title.",
            "is looking for 'magic' and might actually find it. Carry on!",
            "is as warm as a 'Sun-kissed' morning. A great start to every day.",
            "is basically a 'Charm'. Good things follow them around.",
            "is looking for 'respect' and already gives it to everyone they meet.",
            "is as unique as a 'Fingerprint'. One of a kind, in a good way.",
            "is effectively a 'Winner'—and you might be too if you match.",
            "is looking for 'joy' and doesn't think it's a car model.",
            "is as simple as '1-2-3'. No games, no puzzles, just them.",
            "is basically a 'Classic'—the kind that never goes out of style.",
            "is looking for 'purpose' and it's not just 'getting married because auntie said so'.",
            "is as strong as 'Steel'. Can handle the pressure of being normal.",
            "is effectively a 'Treasure'. Hope you have a map!",
            "is looking for 'laughter' and actually has a sense of humor. Rare!",
            "is as honest as a 'Mirror'. What you see is what you get.",
            "is basically a 'Blessing'. Or at least, not a curse.",
            "is looking for 'peace' and doesn't mean 'silence'.",
            "is as steady as a 'Pulse'. The life of the party, but in a calm way.",
            "is effectively a 'Gem'—and we're not talking about the 'Gemini' zodiac sign."
        ]
    },
    honestTake: {
        good: [
            "actually surprisingly good compatibility! This feels suspiciously like a love story hiding in a biodata.",
            "a match made in a very high-end coworking space. You'll synergize your household chores perfectly!",
            "two souls who will argue about the AC temperature for the next 50 years. True love.",
            "a merger that actually makes sense. The family WhatsApp group will be strictly professional.",
            "basically like finding two people who both like the same obscure Netflix series. Fate!",
            "a match that's 90% logic and 10% 'we both hate our relatives'. A solid foundation.",
            "two peas in a pod, if the pod was an expensive apartment in a metro city.",
            "a combination as powerful as chai and Parle-G. Perfectly dipped for success.",
            "basically a 'Power Couple' in the making. Or at least a 'PowerPoint Couple'—very organized.",
            "a match that makes the astrologer's job way too easy. Even the stars are bored.",
            "two people who will definitely agree on where to order dinner from. Is there anything more important?",
            "basically finding your 'other half', provided that other half has a similar tax bracket.",
            "a match so good that even the nosy neighbors will have nothing to gossip about. Disappointing for them!",
            "two souls who will together make 'couple goals' posts that everyone else hates. Congratulations!",
            "basically a 'Seamless' integration of two busy lives. Like a well-oiled machine.",
            "a match that's so compatible, you'll probably start dressing the same within six months.",
            "two people who will definitely survive a 14-hour flight together without a single argument.",
            "basically finding someone who's just as crazy as you are, but in the exact same way.",
            "a match as classic as Shah Rukh Khan and a romantic melody. Pure Bollywood vibes.",
            "two souls who will together build a home that's basically a Pinterest board come to life.",
            "basically a 'Winner'—you've beaten the system and actually found someone decent.",
            "a match that's 100% genuine. No filters, no lies, just two people who actually 'get' each other.",
            "two people who will together achieve everything they've ever wanted, mainly because they're both workaholics.",
            "basically finding the 'missing piece' of your puzzle, and for once, it's not from a different box.",
            "a match as sweet as perfectly made gajar ka halwa. Traditional, heartwarming, and delicious.",
            "two souls who will together navigate the chaos of life with a shared sense of humor.",
            "basically a 'Miracle' in the world of arranged marriages. Cherish it!",
            "a match that's so good, you'll both forget why you were ever worried about being single.",
            "two people who will together make the world a slightly better, or at least a lot funnier, place.",
            "basically finding your 'Person'. The one who makes everything else seem easy.",
            "a match as bright as a Diwali night. Full of light, life, and a few loud celebrations.",
            "two souls who will together create a legacy of love, laughter, and really good family photos.",
            "basically a 'Masterclass' in compatibility. Other couples should take notes.",
            "a match as solid as a 100-year-old banyan tree. Deep roots, strong branches.",
            "two people who will together face every challenge with a 'we got this' attitude.",
            "basically finding someone who makes you feel like you've finally come home.",
            "a match as rare as a quiet day in Mumbai. Unexpected, beautiful, and totally worth it.",
            "two souls who will together build a life that's as colorful as a Holi festival.",
            "basically finding your 'Anchor' in the storm. Steady, reliable, and always there.",
            "a match as harmonious as a perfectly tuned sitar. Every note is in the right place.",
            "two people who will together make even the boring chores of life feel like an adventure.",
            "basically finding the 'Light' at the end of the matrimonial tunnel.",
            "a match as grand as a Big Fat Indian Wedding, but with substance to back up the style.",
            "two souls who will together write a story that's even better than a fairy tale.",
            "basically a 'True' connection. One that goes deeper than just a biodata.",
            "a match as refreshing as a cold lassi on a hot summer day. Pure bliss.",
            "two people who will together make every day feel like a special occasion.",
            "basically finding your 'Partner in Crime'—but like, totally legal crimes, obviously.",
            "a match as timeless as a classic kanchipuram saree. Always elegant, always in style.",
            "two souls who will together create a life that's truly, wonderfully, uniquely theirs."
        ],
        mid: [
            "a fighting chance. Like a startup in its 3rd year—surviving on pure grit and family pressure.",
            "the same success rate as a 5 AM gym resolution. Might last until the honeymoon is over.",
            "two people who will agree to disagree until they both forget what they were fighting about.",
            "a 50-50 shot. May the odds be ever in your favor, because the hormones definitely aren't.",
            "basically like two separate apps that have been forced to integrate. There will be bugs.",
            "a match that's mostly based on 'well, he's tall and she's fair, so why not?'. Typical.",
            "two people who will spend most of their marriage trying to 'change' each other. Good luck with that.",
            "a combination as interesting as water and oil. They coexist, but don't really mix.",
            "basically a 'Transactional' marriage. You bring the package, I bring the homely vibes.",
            "a match that makes the parents happy, but the couple... well, they have Netflix.",
            "two souls who will together navigate life like two separate GPS units giving different directions.",
            "basically finding someone who's 'okay', which is apparently the goal these days.",
            "a match that's 40% love and 60% 'what will people say?'. Ah, tradition!",
            "two people who will together have a 'stable' life, provided nobody asks any deep questions.",
            "basically a 'Compromise' with a fancy wedding album. Smile for the camera!",
            "a match as exciting as a wet firecracker. Looks promising, but might just fizzle out.",
            "two souls who will together build a life that's basically a 'Participation Trophy' of marriages.",
            "basically finding someone who's just as tired of the matrimonial process as you are.",
            "a match as predictable as a rainy day in monsoon. You know what's coming, but you still complain.",
            "two people who will together make 'okay' parents and 'fine' neighbors. Peak mediocrity!",
            "basically a 'Standard' installation. No custom features, just the factory settings.",
            "a match that's 100% 'Arranged'. Every single aspect has been negotiated like a peace treaty.",
            "two souls who will together have a life of 'reasonable' happiness. Could be worse!",
            "basically finding the 'safest' option in a room full of risks. A smart, if boring, choice.",
            "a match as average as a B- on a math test. Not failing, but definitely not an A.",
            "two people who will together spend many years wondering 'is this it?'. Yes, this is it.",
            "basically a 'Work-in-Progress' that's been marked as 'good enough for now'.",
            "a match as functional as a folding chair. Does the job, but not exactly comfortable.",
            "two souls who will together navigate the mundane realities of life with a 'meh' attitude.",
            "basically finding someone who checks 'enough' of the boxes. Box-checking: The true romance!",
            "a match as common as a traffic jam. Frustrating, but part of the daily routine.",
            "two people who will together have a life that's very... symmetrical. No highs, no lows.",
            "basically a 'Safe' harbor. No storms, but also no wind to go anywhere.",
            "a match as plain as unbuttered toast. Edible, but you're always wishing for a topping.",
            "two souls who will together create a life that's basically a rerun of their parents' marriage.",
            "basically finding your 'Equivalent'—not your match, just your equal in boredom.",
            "a match as steady as a dial-up connection. It works, but it's very, very slow.",
            "two people who will together make 'practical' decisions. Romance? No, we have a budget.",
            "basically a 'Roommate' situation with some extra legal paperwork. Convenient!",
            "a match as consistent as a fast-food burger. You know what you're getting, and it's never great.",
            "two souls who will together have a life of 'moderate' satisfaction. Beats being alone!",
            "basically finding someone who doesn't 'annoy' you too much. High standards!",
            "a match as basic as a 'Hello' at a party. A start, but where does it go?",
            "two people who will together build a life of 'expected' outcomes. No surprises here!",
            "basically a 'Placeholder' for a real connection. Maybe it'll grow? Maybe not.",
            "a match as neutral as Switzerland. No wars, but also no passion.",
            "two souls who will together navigate the 'gray areas' of life with a shrug.",
            "basically finding your 'Match' in a box of 1,000 identical items.",
            "a match as reliable as a 'Standard' pencil. Useful, but eventually it needs sharpening.",
            "two people who will together have a life that's... fine. Truly, honestly, just fine."
        ],
        bad: [
            "the same energy as pineapple on pizza. Some people swear by it, but most just wonder why.",
            "about the same chance of working as a 'last warning' from your internet provider.",
            "a disaster movie waiting for a producer. Grab the popcorn and the divorce lawyer's card.",
            "the reason why 'Single' is still a very valid lifestyle choice for both of you.",
            "basically like trying to run 'Windows 95' on a modern Mac. Complete system failure.",
            "a match as harmonious as a cat and a dog in a bathtub. Expect splashing and screams.",
            "two souls who will spend their entire marriage communicating solely through passive-aggressive WhatsApp status updates.",
            "a combination as explosive as sodium and water. Keep away from heat and moisture (and each other).",
            "basically a 'War' disguised as a wedding. Who will surrender first?",
            "a match that makes the neighbors call the police weekly. A lifetime of excitement!",
            "two people who will together navigate life like two ships passing in the night—and then one sinks the other.",
            "basically finding your 'Nemesis' in a matrimonial biodata. Truly special.",
            "a match as sweet as a bitter gourd dipped in vinegar. An acquired taste for no one.",
            "two souls who will together build a home that's basically an 'Escape Room' nobody can escape from.",
            "basically a 'Caution' tape in human form. DO NOT ENTER.",
            "a match as steady as a house of cards in a hurricane. Good luck with the first breeze.",
            "two people who will together have a life of 'maximum' drama. Star Plus is already interested.",
            "basically finding someone who's the exact opposite of everything you ever wanted. Impressive!",
            "a match as stable as a one-legged stool. Hope you have good balance.",
            "two souls who will together create a legacy of 'I told you so's'. A classic romance!",
            "basically a 'Mistake' that's been legalized and celebrated. Bold move.",
            "a match as bright as a black hole. Sucks the happiness out of everyone nearby.",
            "two people who will together navigate life with all the grace of a elephant on ice skates.",
            "basically finding your 'Worst Nightmare' with a high LPA package. Sweet dreams!",
            "a match as romantic as a dental appointment. Painful, expensive, and you just want it to end.",
            "two souls who will together have a life that's basically a 'How-To' guide for what NOT to do.",
            "basically a 'Train Wreck' in slow motion. We can't look away, but we wish we could.",
            "a match as consistent as a politicians' promises. Total fiction.",
            "two people who will together create a home that's basically a 'Fight Club' for two. First rule: don't talk about it.",
            "basically finding the 'final boss' of bad decisions. Congratulations, you've reached the end!",
            "a match as refreshing as a bucket of cold water in winter. Sharp, shocking, and unwelcome.",
            "two souls who will together build a life of 'unending' regret. A unique choice!",
            "basically a 'Blacklist' of compatibility. Everything you shouldn't do, in one place.",
            "a match as silent as an empty room—because you'll have nothing to say to each other.",
            "two people who will together navigate life with the teamwork of two people fighting over a single life jacket.",
            "basically finding your 'Opposite' in a way that's totally, completely wrong.",
            "a match as grand as the Titanic, and with the exact same ending. Watch out for the iceberg!",
            "two souls who will together create a life that's basically a 'Cautionary Tale' for future generations.",
            "basically a 'Disaster'—and we're not talking about the 'movie' genre.",
            "a match as harmonious as a rock in a blender. Loud, messy, and breaks the machine.",
            "two people who will together have a life of 'perfectly' mismatched expectations.",
            "basically finding someone who makes you realize that being alone was actually pretty great.",
            "a match as logical as a dream where you're a fish in a forest. Makes no sense, but here you are.",
            "two souls who will together build a life that's basically a 'Red Flag' factory.",
            "basically a 'Nightmare' with a wedding invite attached. RSVP: No.",
            "a match as warm as a stone in outer space. Cold, dark, and drifting aimlessy.",
            "two people who will together have a life that's basically a 'Never-Ending' argument.",
            "basically finding the 'Wrong' person at the 'Wrong' time in the 'Wrong' way.",
            "a match as classic as a car crash. Tragic, but you can't stop staring.",
            "two souls who will together create a life that's absolutely, positively, 100% wrong for both of you."
        ]
    },
    reactions: {
        hisFamily: [
            "\"Ladki toh theek hai, par package thoda aur hota toh...\" 💸",
            "\"Beta, she earns more than you. Can your ego handle that or should we buy you a gym membership?\" 😬",
            "\"Nuclear family? Who will tell her how to make the perfect round rotis?\" 👵",
            "\"She travels too much... who will manage the house while she's in Bali?\" ✈️",
            "\"Everything is fine, but her height... will the kids be short?\" 📏",
            "\"She's very modern... will she wear a ghoonghat at the village function?\" 👗",
            "\"Her father is a businessman? I hope the dowry—I mean, the 'gifts'—are grand.\" 🎁",
            "\"She has many male friends? Beta, are you sure about this?\" 📱",
            "\"She doesn't know how to cook daal bati? What was her mother teaching her?\" 🥘",
            "\"Everything is good, but her horoscope has a small 'fault'. Pandit ji needs money.\" 🔮",
            "\"She's an only child? Oh, she must be very spoiled. Good luck, beta!\" 🍭",
            "\"She works in night shifts? Who will give you dinner when you come home?\" 🌙",
            "\"Her education is higher than yours... don't let her হয়ে dominance at home.\" 🎓",
            "\"She has a tattoo? Oh my god, what will the neighbors say?\" 🖋️",
            "\"She doesn't want to live with us? But we already decorated her 'duty' room!\" 🏠",
            "\"She's wheatish? The photo looked much fairer. Lighting is a liar!\" 🎨",
            "\"Her family is not from our community? But our traditions are the only 'correct' ones!\" 🚩",
            "\"She's older than you? Beta, you'll be her assistant within a year!\" ⏳",
            "\"Everything is perfect, but I don't like her nose. It's too... opinionated.\" 👃",
            "\"She speaks English at home? Beta, tell her we are 'desi' people here!\" 🗣️",
            "\"She spends too much on shoes? My son's salary is for savings, not sandals!\" 👠",
            "\"She wants a small wedding? But we need to show our power to the whole town!\" 🏰",
            "\"Her mother is very loud... I think the apple hasn't fallen far from the tree.\" 🍎",
            "\"She has a pet dog? No animals in this house! Only humans (and the ones I choose).\" 🐕",
            "\"She doesn't like tea? Is she even a real person? Everyone likes tea!\" ☕",
            "\"Everything is fine, but she's a Gemini. I heard they have two faces. Which one will we see?\" ♊",
            "\"She wants to keep her surname? But then whose name will she use to fight with?\" 📛",
            "\"She's very thin... will she be able to carry a 10kg bucket of water?\" 🪣",
            "\"She's very bubbly... I prefer a girl who stays quiet like a statue.\" 🗿",
            "\"Her family doesn't have a car? How will we arrive at the functions? Walking?\" 🚗",
            "\"She's a designer? We were looking for a 'real' job, like a teacher.\" 🎨",
            "\"Everything is good, but her laugh is too loud. It's 'un-homely'.\" 😂",
            "\"She wears jeans? My son only deserves a girl in a salwar suit 24/7!\" 👖",
            "\"Her brother is in the police? Oh, we have to be extra careful with the 'money' talk.\" 👮",
            "\"She's from a 'posh' area? She'll never adjust to our 'humble' (tiny) apartment.\" 🏢",
            "\"She has short hair? Beta, is she a boy or a girl? I'm confused!\" 💇‍♀️",
            "\"She doesn't follow any 'babas'? How will she know when the world is ending?\" 🧘",
            "\"Everything is fine, but her height... she's taller than you in heels. Sit down, beta!\" 👠",
            "\"She's very ambitious... who will listen to my 4-hour stories about the 80s?\" 📖",
            "\"She has a LinkedIn? Is she looking for a husband or a new manager?\" 💼",
            "\"She's a foodie? My son's salary will go into Zomato and Swiggy!\" 🍔",
            "\"She's a 'fitness freak'? I don't want someone eating salad while I have parathas!\" 🥗",
            "\"Everything is perfect, but her voice... it's too 'independent'.\" 🎙️",
            "\"She's an artist? So she'll be poor but with 'creative' excuses?\" 🎨",
            "\"She doesn't believe in astrology? But my whole life is based on a stone on my finger!\" 💍",
            "\"She's very tech-savvy... she'll probably block me on WhatsApp within a day.\" 🚫",
            "\"Everything is good, but I don't like her parents. They look too 'happy'. Suspicious!\" 😊",
            "\"She's a writer? Oh, so our family secrets will be a best-seller? No thanks!\" 📚",
            "\"She's a morning person? No, we are a family of owls. She'll be too loud at 6 AM!\" 🦉",
            "\"Everything is fine, but she's not a 'homely' girl. She actually has a life!\" 🚩"
        ],
        herFamily: [
            "\"Joint family? Our daughter is a CEO, not a full-time cook for 12 people!\" 🏠",
            "\"Package expectations se match nahi ho raha beta. We need someone more 'settled'.\" 📊",
            "\"Ladka toh sahi hai, bas horoscope match hona chahiye... and the car brand.\" 🔮",
            "\"B.Tech? Is that still a thing? We were hoping for an IAS or at least a Startup Founder.\" 🎓",
            "\"He doesn't want to relocate? Does he think our daughter will live in a village?\" 📍",
            "\"Joint family? My daughter will have to share a bathroom with 8 cousins? Never!\" 🚿",
            "\"His package is 12 LPA? Our driver's son earns 15 LPA. This is embarrassing!\" 💸",
            "\"He lives with his parents? So my daughter will be under surveillance 24/7?\" 🕵️‍♀️",
            "\"He has no hobbies except 'sleeping'? What kind of a boring life is that?\" 🛌",
            "\"Everything is good, but he's not an IITian. My daughter deserves 'branded' brains!\" 🧠",
            "\"He's a 'social' drinker? We know what that means—daily parties!\" 🍺",
            "\"Everything is fine, but he's not a Manglik. My daughter needs someone to blame Mars for!\" ☄️",
            "\"He doesn't own a house? So they'll pay rent to some random landlord? Useless!\" 🏠",
            "\"He's 30 and still a Junior Manager? Where is the 'hustle', beta?\" 💼",
            "\"He has many female friends? Our daughter will be a detective for the rest of her life!\" 🕵️‍♀️",
            "\"He doesn't like to travel? My daughter wants to see the world, not the living room wall!\" ✈️",
            "\"Everything is perfect, but his family is too 'traditional'. They'll make her wear a veil!\" 🧕",
            "\"He's an artist? So my daughter will be the 'bank' while he's the 'dreamer'? No!\" 🎨",
            "\"He has hair on his chest? Oh, it's so 80s movie style. Very un-modern!\" 👕",
            "\"Everything is good, but he's from a different city. Who will help her when she's sick?\" 🤒",
            "\"He has a small car? Our relatives will laugh when they arrive at the wedding!\" 🚗",
            "\"He's very quiet? My daughter needs someone who can argue with the neighbors!\" 🗣️",
            "\"Everything is fine, but his mother looks too 'dominant'. My daughter is a queen!\" 👑",
            "\"He has no Instagram? Is he even real? He could be a ghost!\" 👻",
            "\"He says he's a 'foodie'? That means our daughter will be in the kitchen non-stop!\" 🥘",
            "\"Everything is perfect, but he's a Scorpio. I heard they are very 'deep'. Too much drama!\" 🦂",
            "\"He wants to live in a nuclear family? But who will babysit for free?\" 👶",
            "\"He's a gamer? So he'll be fighting virtual monsters while our daughter fights reality?\" 🎮",
            "\"Everything is good, but he doesn't know how to fix a light bulb. Un-manly!\" 💡",
            "\"He's a 'nature lover'? That means he'll take our daughter to forests instead of malls!\" 🌲",
            "\"Everything is fine, but he's too 'modern'. He might want to split the bills!\" 💸",
            "\"He has a tattoo? Oh, he must be a 'bad boy'. My daughter needs a 'good' boy!\" 🖋️",
            "\"Everything is perfect, but his height... he's only 5.8. My daughter is 5.7 in flats!\" 📏",
            "\"He works in a startup? So he could be unemployed by next Tuesday? No way!\" 📉",
            "\"Everything is good, but he doesn't believe in God. Who will he tell to 'please' make him rich?\" 🛐",
            "\"He's very thin? Can he even lift a gas cylinder?\" 🪣",
            "\"Everything is fine, but his laugh is too loud. Our neighbors are 'classy' people!\" 😂",
            "\"He wears shorts in public? My daughter deserves a man who wears a suit to the grocery store!\" 👔",
            "\"Everything is perfect, but he's an only child. He'll expect our daughter to be his second mother!\" 🍼",
            "\"He's very ambitious... he'll probably forget our daughter's birthday within a year!\" 🎂",
            "\"Everything is good, but his family has too many 'rules'. My daughter is a free bird!\" 🕊️",
            "\"He's a 'fitness freak'? So he'll judge our daughter's third helping of butter chicken?\" 🍗",
            "\"Everything is perfect, but his voice is too soft. How will he protect her from the society?\" 🎙️",
            "\"He's a 'social' person? He'll be more on his phone than with her!\" 📱",
            "\"Everything is good, but he doesn't like dogs. Dogs are better than most relatives!\" 🐕",
            "\"He has short hair? But we liked the 'man-bun' look from the other guy!\" 💇‍♂️",
            "\"Everything is fine, but he's not a Gemini. Geminis are so 'exciting'!\" ♊",
            "\"He wants a small wedding? But we have 5,000 people to impress!\" 🏰",
            "\"Everything is good, but he's a 'writer'. So he'll be poor but with 'deep' thoughts?\" 📚",
            "\"Everything is perfect, but he doesn't like tea. Who doesn't like tea?! Scandalous!\" ☕"
        ]
    },
    regionalRoasts: {
        mumbai: [
            "🏙️ Mumbai native - You'll spend 4 hours in local trains just to meet for a 20-min coffee. That's true commitment.",
            "🏠 Lives in Mumbai - You're basically looking for a partner with enough space for a 1BHK that costs more than a private island.",
            "🚈 'Mumbaikar' - Your personality is basically 80% struggle and 20% Vada Pav. Honestly, we respect it.",
            "🚗 Thinks a 10km commute in 2 hours is 'normal'. Beta, your patience is elite, but your logic is missing."
        ],
        delhi: [
            "🚙 Delhi vibe - 'Tu jaanta hai mera baap kaun hai?' energy is strong here. We hope the partner knows too.",
            "🧥 Delhi native - You probably have more winter jackets than actual friends. Show-off level: High.",
            "🗣️ Delhi directness - You're not being 'honest', you're being a human loudspeaker. Tone it down, ji!",
            "🍽️ Thinks the only real food in the world is North Indian. Your taste buds are as narrow as your requirements."
        ],
        bangalore: [
            "💻 Bangalore Tech Bro - Your wedding invitation will probably be an NFT or a GitHub repo. Keep the 'synergy' away.",
            "🚦 Bangalore native - You'll be late to your own wedding because of Silk Board traffic. Plan 3 days in advance.",
            "🌙 Early sleeper - You're in bed by 10 PM while the rest of the country is living. Boring, but healthy?",
            "🏢 'Startup Founder' vibe - You don't want a marriage, you want a co-founder with a high valuation."
        ],
        hyderabad: [
            "🍛 Hyderabad native - If the wedding doesn't have 5 types of Biryani, is it even a wedding? Priorities!",
            "🐢 Hyderabad pace - You move slower than a government file. Life is not a 'light' tea break, wake up!",
            "💻 Madhapur IT vibe - Another software engineer from Hyderabad. So original, it deserves its own boring award."
        ],
        pune: [
            "😴 2 PM to 4 PM Pune nap - Your commitment to sleeping is more stable than your career. Don't call us during break time.",
            "🎭 Pune culture vs IT - You think you're an intellectual, but you're just a techie who reads Wikipedia. Calm down.",
            "📏 Puneri Patya energy - You have a list of 'No Entry' rules for your partner that's longer than the Constitution."
        ],
        chennai: [
            "☕ Chennai native - Filters in your coffee, but zero filters in your traditional expectations. Dial it back, mama!",
            "🎬 Cinema craze - If your partner doesn't like Thala or Thalapathy, the marriage is basically over before it starts.",
            "🎓 Chennai intellectual - You judge people by their math marks from 10th grade. Beta, it's 2025, let it go."
        ],
        kolkata: [
            "📖 Kolkata intellectual - You'll spend the whole honeymoon debating world politics and cinema. Poor partner.",
            "🍬 Mishti lover - You're sweet, but your arguments are as complicated as a Satyajit Ray plot twist.",
            "⚽ Football craze - You'll definitely skip the anniversary if East Bengal vs Mohun Bagan is on."
        ],
        ahmedabad: [
            "💸 Ahmedabad native - Every conversation ends in 'Profit kitna hai?'. You don't want a partner, you want a portfolio.",
            "🥨 Thinks everything needs sugar, even life. You're too sweet for your own good—literally.",
            "🛍️ 'Business Mind' - You'll negotiate the dowry—sorry, 'gifts'—better than a Share Bazar shark."
        ]
    }
};
